### ISSUE TITLE
tracker_project_name error in train.py (sd-base)

### ISSUE THREAD

**Issue by jessie-chen99** [HighCWu/control-lora-v3#5]
Hi thanks for your project. But when I tried to run train.py following readme, an error occured. I am using default args.tracker_project_name so I am confused. Could you please help me solve this? Thanks a lot!
![image](https://github.com/user-attachments/assets/9db45c62-4633-4814-ba2d-0908bd042bdf)

![image](https://github.com/user-attachments/assets/a2450b12-4f68-4861-ab6f-8ba5fac01ed4)

**Comment by HighCWu** [comment]
I'm sorry that I'm not sure what's going on with this. My code is basically modified from [diffusers/examples/controlnet/train_controlnet.py](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py).
I suspect it may be a version problem of `accelerator`. You can try to run the official example of `diffusers `to see if the same issue occurs.

**Comment by jessie-chen99** [comment]
Thanks, I run the official example of `diffusers/examples/controlnet/train_controlnet.py` with same commands and it works well. Should I change my `accelerator config` when training your lora project? My accelerate version is `0.34.2` and config is like this now.
![image](https://github.com/user-attachments/assets/61ebb50d-133b-4f37-8513-cb29927ca991)

**Comment by HighCWu** [comment]
I checked it carefully, it may be because you use tensorboard, I have not used tensorboard before. tensorboard cannot handle list types for config. I added two lists in args in my code. Now you can add the following code above the error, which may solve the problem.
```py
    tracker_config.pop("extra_lora_rank_modules")
    tracker_config.pop("extra_lora_ranks")
```
If the problem persists, try using wandb instead of tensorboard.

**Comment by jessie-chen99** [comment]
Thank you!! The issue was indeed due to `args.report_to` using default setting `tensorbroad`. And both of the solutions you mentioned are effective.👍
