### ISSUE TITLE
args.half_or_full_lora can't set to full

### ISSUE THREAD

**Issue by jessie-chen99** [HighCWu/control-lora-v3#6]
Hello, I just change the `args.half_or_full_lora`  from `half_skip_attn` to `full` and run train.py. Then a dtype issue occurs. Do you know how to fix this? Thanks!

![image](https://github.com/user-attachments/assets/0f78d3dc-c6ed-4b25-8c1a-cce7568ab131)

**Comment by HighCWu** [comment]
try to disable xformer attention
